### ISSUE TITLE
Device Settings are not translated

### ISSUE THREAD

**Issue by franck-fourel** [coyotte508/viz#2]
Most of the items in device settings are not translated.
![devicesettings](https://user-images.githubusercontent.com/22294614/39199685-5cef42dc-47ea-11e8-8226-280a8b386cfe.PNG)

**Comment by coyotte508** [comment]
Done in https://github.com/coyotte508/viz/commit/f2b3b40eecc8878c2074714d7da3c52f41eecd63

**Comment by franck-fourel** [comment]
Looks good to me
