### ISSUE TITLE
print button keeps loading after switching language 

### ISSUE THREAD

**Issue by franck-fourel** [coyotte508/viz#4]
the print button is disabled and it does not display the print logo after changing the language. 

![printbutton](https://user-images.githubusercontent.com/22294614/39200093-6ece2d6e-47eb-11e8-8832-1d0d6187e56b.PNG)

**Comment by coyotte508** [comment]
This is due to an error. It's possibly due to uploading new device data. Regarding the viz error reported yesterday (about `patient.profile`), I overwrote the last commit ( https://github.com/coyotte508/viz/commit/823ee7f4fd414fb2558d5b0dc52f9f29a423b642 ).

**Comment by franck-fourel** [comment]
Still the same issue when switching to a french: the print logo keeps running.

**Comment by coyotte508** [comment]
I think viz is sensitive in regards to the length of text.

For example, if you just add this translation:

`"Interrupted": "translation.json_264",`

An error occurs. With this instead, there are no errors:

`"Interrupted": "Interrompu",`

Of course this is not the only key, there are other keys that cause problems (below `"Interrupted"` in alphabetical order), but I don't think it's something I can find a solution for.

**Comment by franck-fourel** [comment]
looks good as I cannot reproduce the issue
