### ISSUE TITLE
Print button is not taking language defined in profile

### ISSUE THREAD

**Issue by franck-fourel** [coyotte508/viz#5]
The generate pdf button is not taking the language defined in user profile. 
![tidepoolprint](https://user-images.githubusercontent.com/22294614/39426978-47a54164-4c82-11e8-9170-17eb9e511b34.PNG)

The pdf is generated in English.

**Comment by coyotte508** [comment]
Language is now in preferences->displayLanguageCode, as per the change requested in the blip language pull request.

Viz and Blip both need to be up to date (last commit around Friday afternoon). I think here viz is up-to-date, but maybe blip is not.

You will also need to do `export I18N_ENABLED=true` to show language selection in blip after the update.

**Comment by franck-fourel** [comment]
looks good now
